name: CTests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    container: golang:1.19.4
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: |
          go build -buildmode=c-archive -o ios/libpolygonid-linux-amd64.a ./cmd/polygonid
          cp ios/libpolygonid-linux-amd64.h ios/libpolygonid-darwin-arm64.h
          cd examples/
          mkdir build
          cd build
          cmake ..
          make
          make test ARGS="--rerun-failed --output-on-failure"
