name: CTests

on:
  release:
    types: [published]
  push:
    branches:
      - main
  pull_request:

jobs:

  integration-test-linux:
    strategy:
      matrix:
        containers:
          - 1.24.2-bookworm
    runs-on: ubuntu-24.04
    container: golang:${{matrix.containers}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: |
          apt-get update
          apt-get install -y cmake libcjson-dev
          # without this line `git status` does not work on containers
          # 1.19.5 and upper
          git config --global --add safe.directory `pwd`
          go build -tags no_jwz -buildmode=c-archive -o ios/libpolygonid.a ./cmd/polygonid
          cp ios/libpolygonid.h ios/libpolygonid-darwin-arm64.h
          mkdir examples/build
          cd examples/build
          cmake ..
          make
          make test ARGS="--rerun-failed --output-on-failure"

  integration-test-macos:
    runs-on: macos-14
    if: github.event_name == 'push' || github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run ctests
        run: |
          go build -tags no_jwz -buildmode=c-archive -o ios/libpolygonid.a ./cmd/polygonid
          cp ios/libpolygonid.h ios/libpolygonid-darwin-arm64.h
          brew install cjson
          mkdir examples/build
          cd examples/build
          cmake ..
          make
          make test ARGS="--rerun-failed --output-on-failure"
      - name: Check the ios-arm64 build
        run: make ios-arm64
      - name: Check the ios-simulator build
        run: make ios-simulator
      - name: Check the android-armeabi-v7a build
        run: make android-armeabi-v7a
      - name: Check the android-arm64-v8a build
        run: make android-arm64-v8a
      - name: Check the android-x86 build
        run: make android-x86
      - name: Check the android-x86-64 build
        run: make android-x86-64

      - name: Create multiplatform bundle for iOS
        if: github.event_name == 'release'
        run: make ios

      - name: Prepare release artifacts
        if: github.event_name == 'release'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -x
          mkdir libpolygonid-${{ github.ref_name }}
          cp -r ios android libpolygonid-${{ github.ref_name }}/
          zip -r libpolygonid-${{ github.ref_name }}.zip libpolygonid-${{ github.ref_name }}
          gh release upload ${{ github.event.release.tag_name }} libpolygonid-${{ github.ref_name }}.zip

      # These steps goes after archiving release artifacts as I don't want to
      # put these libs into release zip.
      - name: Check the dylib build
        run: make dylib
      - name: Check the darwin-arm64 build
        run: make darwin-arm64
