name: CTests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration-test-linux:
    strategy:
      matrix:
        containers:
          - 1.19.6-bullseye
          - 1.20.1-bullseye
    runs-on: ubuntu-22.04
    container: golang:${{matrix.containers}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: |
          apt-get update
          apt-get install -y cmake libcjson-dev
          # without this line `git status` does not work on containers
          # 1.19.5 and upper
          git config --global --add safe.directory `pwd`
          go build -buildmode=c-archive -o ios/libpolygonid.a ./cmd/polygonid
          cp ios/libpolygonid.h ios/libpolygonid-darwin-arm64.h
          mkdir examples/build
          cd examples/build
          cmake ..
          make
          make test ARGS="--rerun-failed --output-on-failure"
  integration-test-macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.1
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: |
          go build -buildmode=c-archive -o ios/libpolygonid.a ./cmd/polygonid
          cp ios/libpolygonid.h ios/libpolygonid-darwin-arm64.h
          brew install cjson
          mkdir examples/build
          cd examples/build
          cmake ..
          make
          make test ARGS="--rerun-failed --output-on-failure"
  compilation-test-macos:
    strategy:
      matrix:
        targets:
          - ios-arm64
          - ios-simulator
          - darwin-arm64
          - dylib
          - android-armeabi-v7a
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.1
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: make ${{matrix.containers}}
