name: CTests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        containers:
          - 1.19.5-bullseye
          - 1.20.0-bullseye
    runs-on: ubuntu-22.04
    container: golang:${{matrix.containers}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: |
          apt-get update
          apt-get install -y cmake libcjson-dev
          go build -buildmode=c-archive -o ios/libpolygonid.a ./cmd/polygonid
          cp ios/libpolygonid.h ios/libpolygonid-darwin-arm64.h
          mkdir examples/build
          cd examples/build
          cmake ..
          make
          make test ARGS="--rerun-failed --output-on-failure"
  test-macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.0
#      - uses: actions/cache@v3
#        with:
#          path: |
#            ~/.cache/go-build
#            /go/pkg/mod
#          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-go-
      - run: |
          go version
          go build -buildmode=c-archive -o ios/libpolygonid.a ./cmd/polygonid
